"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var myLista_1 = require("./EstructurasDinamicas/myLista");
var pacientes_1 = require("./EstructurasDinamicas/pacientes");
var miLista = new myLista_1.default();
var unPaciente1 = new pacientes_1.default("1", "Julio", "Lopez", "Rivadavia 233", "1215566");
var unPaciente2 = new pacientes_1.default("2", "Amalia", "Lopez", "Rivadavia 233", "1215566");
var unPaciente3 = new pacientes_1.default("3", "Eduardo", "Dominguez", "Florida 450", "1215566");
// const unNodo1 : MyNode<Paciente> = new MyNode<Paciente>( unPaciente1);
// const unNodo3 : MyNode<Paciente> = new MyNode<Paciente>( unPaciente3);
// const unNodo2 : MyNode<Paciente> = new MyNode<Paciente>( unPaciente2);
console.log("Insertando paciente 3");
miLista.insertFirst(unPaciente3);
console.log("Insertando paciente 2");
miLista.insertFirst(unPaciente2);
console.log("Insertando paciente 1");
miLista.insertFirst(unPaciente1);
console.log("Imprimiendo a todos los pacientes....");
miLista.imprimirTodo();
console.log("Eliminando paciente 2");
miLista.delete(unPaciente2);
console.log("Imprimiendo a todos los pacientes....");
miLista.imprimirTodo();
console.log("Actualizando el código del paciente 1");
var pacienteEditado = miLista.search(unPaciente1);
pacienteEditado.value.codigo = "1410";
console.log("Imprimiendo a todos los pacientes....");
miLista.imprimirTodo();
var otroNuevoPaciente = new pacientes_1.default("4", "Omar", "Gonzalez", "Fake 123", "555-4444108000");
console.log("Agregando otro nuevo paciente después del 1...");
miLista.insertarElementoDespuesDe(otroNuevoPaciente, unPaciente1);
console.log("Imprimiendo a todos los pacientes....");
miLista.imprimirTodo();
